/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compatibility validation endpoint */
        post: operations["validateCompat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a FHIR resource */
        post: operations["validateV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service capabilities and supported options */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Warmup validator context and optional IGs */
        post: operations["warmup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness status */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective runtime configuration */
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValueRow: {
            value?: string;
        };
        ValidateOptions: {
            label?: string;
            /** @example 4.0.1 */
            fhir_version: string;
            /** @enum {string} */
            source_format: "json" | "xml";
            implementation_guides?: components["schemas"]["ValueRow"][];
            profiles?: components["schemas"]["ValueRow"][];
            bundle_target?: string;
            bundle_profile?: string;
            /** @description Use n/a to disable terminology server */
            terminology_server?: string;
            /** @description Use n/a to disable terminology cache */
            terminology_cache?: string;
            /**
             * @default json
             * @enum {string}
             */
            output_style: "json";
            /** @enum {string} */
            severity_floor?: "hint" | "warning" | "error";
            /** @enum {string} */
            best_practice?: "ignore" | "hint" | "warning" | "error";
            native_schema?: boolean;
            check_references?: boolean;
            ig_recurse?: boolean;
            /** Format: int64 */
            validation_timeout_ms?: number;
            /** Format: int32 */
            max_validation_messages?: number;
        };
        ValidateRequest: {
            opts: components["schemas"]["ValidateOptions"];
            /**
             * Format: byte
             * @description Base64-encoded FHIR resource bytes (JSON or XML)
             */
            resourceBase64: string;
        };
        ValidateResponse: {
            valid?: boolean;
            /**
             * Format: byte
             * @description Base64-encoded OperationOutcome JSON
             */
            outcomeBase64?: string;
            /** Format: int32 */
            exitCode?: number;
            stderr?: string;
            /** Format: int64 */
            durationMs?: number;
            requestId?: string;
            errorCode?: string;
            errorMessage?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: WithRequired<components["schemas"]["ValidateResponse"], "errorCode" | "errorMessage" | "requestId">;
        WarmupRequest: {
            /** @example 4.0.1 */
            fhir_version?: string;
            implementation_guides?: components["schemas"]["ValueRow"][];
        };
        WarmupResponse: {
            warmed?: boolean;
            /** Format: int64 */
            durationMs?: number;
            requestId?: string;
            message?: string;
        };
        ReadyResponse: {
            ready?: boolean;
            maxConcurrency?: number;
            availablePermits?: number;
            terminologyMode?: string;
            status?: string;
        };
        RuntimeConfigResponse: {
            maxConcurrency?: number;
            /** Format: int64 */
            maxRequestBodyBytes?: number;
            prometheusEnabled?: boolean;
            openApiPath?: string;
        };
        CapabilitiesResponse: {
            service?: string;
            version?: string;
            endpoints?: string[];
            supportedFhirVersions?: string[];
            invariants?: {
                [key: string]: string;
            };
            options?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validateCompat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Invalid request payload or options */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal validation error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validateV1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Invalid request payload or options */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal validation error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capabilities returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    warmup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WarmupRequest"];
            };
        };
        responses: {
            /** @description Warmup completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarmupResponse"];
                };
            };
            /** @description Invalid warmup request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfigResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
